//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHASTANE.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_iletisim
    {
        public int iletisimid { get; set; }
        public string iletisimadsoyad { get; set; }
        public string iletisimmail { get; set; }
        public string iletisimkonu { get; set; }
        public string iletisimmesaj { get; set; }
    }
}
