//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHASTANE.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_randevu
    {
        public int randevuid { get; set; }
        public string randevuadsoyad { get; set; }
        public string randevutcno { get; set; }
        public string randevutel { get; set; }
        public Nullable<int> randevudoktorid { get; set; }
        public Nullable<int> randevubolumid { get; set; }
        public Nullable<System.DateTime> randevutarihsaat { get; set; }
        public Nullable<int> randevuhastaid { get; set; }
    
        public virtual tbl_bolum tbl_bolum { get; set; }
        public virtual tbl_doktor tbl_doktor { get; set; }
        public virtual tbl_hasta tbl_hasta { get; set; }
    }
}
