//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHASTANE.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hasta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_hasta()
        {
            this.tbl_randevu = new HashSet<tbl_randevu>();
        }
    
        public int hastaid { get; set; }
        public string hastaadsoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_randevu> tbl_randevu { get; set; }
    }
}
