//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCHASTANE.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_giris
    {
        public int kullaniciid { get; set; }
        public string kullaniciad { get; set; }
        public string kullanicisifre { get; set; }
    }
}
